name: conn_pool
description: Manages a pool of connections based several builtin strategies.
version: 2.1.8
homepage: https://github.com/Jaguar-dart/db
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.3.0
