name: jaguar
version: 0.3.1
description: jaguar is a performant server side framework
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  yaml: ^2.1.12
  args: ">=0.13.7 <0.14.0"
  http_server: ">=0.9.6 <0.10.0"
  mime: ">=0.9.3 <0.10.0"
  logging: ">=0.11.3 <0.12.0"
  intl: ">=0.14.0 <0.15.0"
  stack_trace: '>=1.7.0 <2.0.0'

dev_dependencies:
  cookies:
  test: 0.12.15+10
