name: jaguar_auth
description: Authentication interceptors and helper functions for Jaguar
version: 2.2.2
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://jaguar-dart.github.io/

documentation:

environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

dependencies:
  jaguar: ^2.2.10
  jaguar_common: ^2.1.4
  crypto: ^2.0.3

dev_dependencies:
  test: ^1.3.0
  http: ^0.11.3
  jaguar_reflect: ^2.2.0
  jaguar_resty: ^2.6.2
  jaguar_client: ^2.2.1
  jaguar_example_session_models: ^2.1.6