name: jaguar_dev_proxy
description: Jaguar reverse proxy implementation for dev
version: 2.4.2
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://jaguar-dart.github.io/

documentation:

environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

dependencies:
  jaguar: ^2.4.14
  path: ^1.6.2

dev_dependencies:
  test: ^1.3.0
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.1