name: jaguar
version: 2.4.34
description: Jaguar is a production ready HTTP server framework built for speed, simplicity and extensiblity
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://jaguar-dart.github.io

documentation:

environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

dependencies:
  http_server: ^0.9.7
  mime: ^0.9.6
  logging: ^0.11.3
  stack_trace: ^1.9.2
  path: ^1.6.1
  collection: ^1.14.6
  crypto: ^2.0.5
  auth_header: ^2.1.2
  jaguar_common: ^2.1.1
  path_tree: ^2.2.2
  jaguar_serializer: ^2.2.8
  meta: ">1.1.0 <2.0.0"

dev_dependencies:
  analyzer: ^0.32.0
  test: ^1.5.1
  jaguar_resty: ^2.10.1
  http: ^0.12.0
  client_cookie: ^2.1.5
  http_parser: