name: jaguar
version: 3.1.1
description: Jaguar is a production ready HTTP server framework built for speed, simplicity and extensiblity
homepage: https://jaguar-dart.github.io
repository: https://github.com/Jaguar-dart/jaguar

documentation:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http_server: ^1.0.0
  mime: ^1.0.1
  logging: ^1.0.2
  stack_trace: ^1.10.0
  path: ^1.8.1
  collection: ^1.15.0
  crypto: ^3.0.1
  auth_header: ^3.0.1
  jaguar_common: ^3.0.0
  path_tree: ^3.0.0
  meta: ^1.7.0

dev_dependencies:
  test: ^1.20.1
  jaguar_resty: ^3.0.0
  http: ^0.13.4
  client_cookie: ^3.0.2
  http_parser:
